services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  dispatcher_service:
    build: ./backend/dispatcher_service
    volumes:
      - ./backend/dispatcher_service:/app
    depends_on:
      - kafka
    restart: always
    environment:
      PYTHONUNBUFFERED: '1'
      KAFKA_BOOTSTRAP: kafka:9092


  send_test_service:
    build: ./backend/send_test_service
    volumes:
      - ./backend/send_test_service:/app
    depends_on:
      - kafka
    restart: always
    environment:
      PYTHONUNBUFFERED: '1'
      KAFKA_BOOTSTRAP: kafka:9092